Repository 2-6-collaborative-project/Mounteam_BE, pull requests merged in 2024-04, with the labels that each got.

#90 Feat : 내 모임 보기, 내 피드 보기 무한 스크롤
  src/main/java/com/example/mountain/config/QuerydslConfiguration.java
  src/main/java/com/example/mountain/domain/feed/repository/FeedRepositoryCustom.java
  src/main/java/com/example/mountain/domain/feed/repository/FeedRepositoryImpl.java
  src/main/java/com/example/mountain/domain/team/entity/Team.java
  src/main/java/com/example/mountain/domain/team/repository/TeamRepository.java
  src/main/java/com/example/mountain/domain/team/repository/TeamRepositoryCustom.java
  src/main/java/com/example/mountain/domain/team/repository/TeamRepositoryImpl.java
  src/main/java/com/example/mountain/domain/user/controller/UserController.java
  src/main/java/com/example/mountain/domain/user/entity/User.java
  src/main/java/com/example/mountain/domain/user/service/UserService.java
  src/main/java/com/example/mountain/global/error/ErrorCode.java
  src/main/java/com/example/mountain/oauth/jwt/AuthTokensGenerator.java
  src/main/java/com/example/mountain/oauth/jwt/TokenAuthenticationFilter.java
  src/main/java/com/example/mountain/oauth/jwt/service/TokenService.java
Labels: 기능 개발, 기능 추가

#93 Fix: 네이밍 변경, mountain x,y좌표 도입
  src/main/java/com/example/mountain/domain/curation/dto/SeasonResponse.java
  src/main/java/com/example/mountain/domain/feed/dto/response/FeedListResponse.java
  src/main/java/com/example/mountain/domain/review/dto/response/ReviewListResponse.java
  src/main/java/com/example/mountain/domain/review/dto/response/TeamReviewDetailResponse.java
  src/main/java/com/example/mountain/domain/review/dto/response/TeamReviewListResponse.java
  src/main/resources/application.yml
Labels: 기능 수정

#96 Fix 무한 스크롤 수정
  src/main/java/com/example/mountain/domain/feed/dto/response/FeedListScrollResponse.java
  src/main/java/com/example/mountain/domain/feed/repository/FeedRepositoryCustom.java
  src/main/java/com/example/mountain/domain/feed/repository/FeedRepositoryImpl.java
  src/main/java/com/example/mountain/domain/team/dto/response/TeamListScrollResponse.java
  src/main/java/com/example/mountain/domain/team/repository/TeamRepositoryCustom.java
  src/main/java/com/example/mountain/domain/team/repository/TeamRepositoryImpl.java
  src/main/java/com/example/mountain/domain/user/dto/UserMyProfileDto.java
  src/main/java/com/example/mountain/domain/user/service/UserService.java
  src/main/resources/application.yml
Labels: 기능 수정

#97 Feat: 모임 이미지 도입
  src/main/java/com/example/mountain/domain/curation/dto/SeasonResponse.java
  src/main/java/com/example/mountain/domain/feed/dto/response/FeedListResponse.java
  src/main/java/com/example/mountain/domain/image/entity/Image.java
  src/main/java/com/example/mountain/domain/review/dto/response/ReviewListResponse.java
  src/main/java/com/example/mountain/domain/team/controller/TeamController.java
  src/main/java/com/example/mountain/domain/team/dto/request/TeamUpdateRequest.java
  src/main/java/com/example/mountain/domain/team/dto/response/TeamDetailResponse.java
  src/main/java/com/example/mountain/domain/team/dto/response/TeamInfoResponse.java
  src/main/java/com/example/mountain/domain/team/dto/response/TeamListResponse.java
  src/main/java/com/example/mountain/domain/team/entity/Team.java
  src/main/java/com/example/mountain/domain/team/service/TeamService.java
  src/main/java/com/example/mountain/global/aws/S3Service.java
  src/main/java/com/example/mountain/global/error/ErrorCode.java
Labels: 기능 추가

#121 feat : s3 프로필 이미지 수정, 삭제
  src/main/java/com/example/mountain/domain/user/controller/UserController.java
  src/main/java/com/example/mountain/domain/user/dto/UserUpdateProfileDto.java
  src/main/java/com/example/mountain/domain/user/service/UserService.java
  src/main/java/com/example/mountain/global/aws/S3Service.java
Labels: 기능 개발, 기능 추가
